Fixes hpm search
Search currently fails because there is one package without a description (hyper-dark-vibrancy)

```$ hpm search vibrancy
✖ Searching
TypeError: Cannot read property 'toLowerCase' of null```